version: '3.7'
services:
  postgres:
    image: postgres:9.6
    env_file:
      - .env
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    logging:
      options:
        max-size: 10m
        max-file: "3"
  webserver:
    image: geoscienceaustralia/airflow
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - LOAD_EX=n
      # Uncomment and add fernet key to encrypt/decrypt secrets. For details see
      # https://airflow.readthedocs.io/en/stable/howto/secure-connections.html
      # - FERNET_KEY=<insert-fernet-key-here>
      - EXECUTOR=Local
      - AIRFLOW__SMTP__SMTP_HOST=maildev
      - AIRFLOW__CORE__ENABLE_XCOM_PICKLING=False
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
      - ./scripts:/usr/local/airflow/scripts
      - ./requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
  maildev:
    image: maildev/maildev
    ports:
      - "1080:80"
